# frozen_string_literal: true

require "spec_helper"

RSpec.describe "Associations" do
  describe "belongs_to association" do
    before do
      # Create parent table
      connection = ActiveRecord::Base.connection
      connection.execute(<<-SQL)
        CREATE TABLE AUTHORS (
          ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          NAME BLOB SUB_TYPE TEXT,
          CREATED_AT TIMESTAMP,
          UPDATED_AT TIMESTAMP
        )
      SQL

      connection.execute(<<-SQL)
        CREATE TABLE BOOKS (
          ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          TITLE BLOB SUB_TYPE TEXT,
          AUTHOR_ID BIGINT,
          CREATED_AT TIMESTAMP,
          UPDATED_AT TIMESTAMP,
          FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID)
        )
      SQL

      # Define models
      Object.send(:remove_const, :Author) if defined?(Author)
      Object.send(:remove_const, :Book) if defined?(Book)

      class Author < ActiveRecord::Base
        has_many :books
      end

      class Book < ActiveRecord::Base
        belongs_to :author
      end

      Author.reset_column_information
      Book.reset_column_information
    end

    after do
      connection = ActiveRecord::Base.connection
      connection.drop_table :books, if_exists: true
      connection.drop_table :authors, if_exists: true
    end

    it "creates and retrieves associated records" do
      author = Author.create!(name: "John Doe")
      book = Book.create!(title: "My Book", author: author)

      expect(book.author).to eq(author)
      expect(author.books).to include(book)
    end
  end

  describe "has_many association" do
    before do
      connection = ActiveRecord::Base.connection
      connection.execute(<<-SQL)
        CREATE TABLE USERS (
          ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          NAME BLOB SUB_TYPE TEXT,
          CREATED_AT TIMESTAMP,
          UPDATED_AT TIMESTAMP
        )
      SQL

      connection.execute(<<-SQL)
        CREATE TABLE POSTS (
          ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          TITLE BLOB SUB_TYPE TEXT,
          USER_ID BIGINT,
          CREATED_AT TIMESTAMP,
          UPDATED_AT TIMESTAMP,
          FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
        )
      SQL

      Object.send(:remove_const, :User) if defined?(User)
      Object.send(:remove_const, :Post) if defined?(Post)

      class User < ActiveRecord::Base
        has_many :posts
      end

      class Post < ActiveRecord::Base
        belongs_to :user
      end

      User.reset_column_information
      Post.reset_column_information
    end

    after do
      connection = ActiveRecord::Base.connection
      connection.drop_table :posts, if_exists: true
      connection.drop_table :users, if_exists: true
    end

    it "creates and retrieves has_many records" do
      user = User.create!(name: "Alice")
      post1 = Post.create!(title: "Post 1", user: user)
      post2 = Post.create!(title: "Post 2", user: user)

      expect(user.posts.count).to eq(2)
      expect(user.posts).to include(post1, post2)
    end

    it "supports has_many with conditions" do
      user = User.create!(name: "Bob")
      Post.create!(title: "Active Post", user: user)
      Post.create!(title: "Draft Post", user: user)

      expect(user.posts.count).to eq(2)
    end
  end
end
