# frozen_string_literal: true

# spec/spec_helper.rb
require "bundler/setup"

# Load Rails environment for adapter registration
require "active_record"
require "fb"
require "firebird_adapter"
require "rspec"

# Configure database connection
DB_PATH = ENV["FIREBIRD_DATABASE"] || File.expand_path("test.fdb", __dir__)
fb_host = ENV["FIREBIRD_HOST"] || ENV["DB_HOST"] || "localhost"
fb_port = ENV["FIREBIRD_PORT"] || 3050
fb_host_with_port = fb_host.include?(":") ? fb_host : "#{fb_host}/#{fb_port}"

DB_CONFIG = {
  adapter: "firebird",
  database: DB_PATH,
  username: ENV["FIREBIRD_USER"] || "sysdba",
  password: ENV["FIREBIRD_PASSWORD"] || "masterkey",
  charset: "UTF8",
  downcase: false,
  host: fb_host_with_port
}.freeze

is_local_db = !ENV["FIREBIRD_HOST"] && !ENV["DB_HOST"] && !DB_PATH.include?(":")

# Clean local test database if it exists
File.delete(DB_PATH) if is_local_db && File.exist?(DB_PATH)

# Create database if needed
if is_local_db || !File.exist?(DB_PATH)
  begin
    ::Fb::Database.create(
      database: DB_PATH,
      user: ENV["FIREBIRD_USER"] || "SYSDBA",
      password: ENV["FIREBIRD_PASSWORD"] || "masterkey"
    )
    puts "✓ Test database created at #{DB_PATH}"
  rescue StandardError => e
    puts "Note: Database may already exist or is remote: #{e.message}"
  end
end

# Configure RSpec
RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups
  config.filter_run_when_matching :focus

  config.before(:suite) do
    # Establish connection
    ActiveRecord::Base.establish_connection(DB_CONFIG)
    connection = ActiveRecord::Base.connection

    # Create test table - Firebird stores names in uppercase internally
    unless connection.table_exists?(:sis_tests)
      connection.execute(<<-SQL)
        CREATE TABLE SIS_TESTS (
          ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          FIELD_VARCHAR BLOB SUB_TYPE TEXT,
          FIELD_CHAR CHAR(10),
          FIELD_DATE DATE,
          FIELD_SMALLINT INTEGER,
          FIELD_INTEGER INTEGER,
          FIELD_DOUBLE_PRECISION DOUBLE PRECISION,
          FIELD_BLOB_TEXT BLOB SUB_TYPE TEXT,
          FIELD_BLOB_BINARY BLOB SUB_TYPE BINARY,
          FIELD_BOOLEAN BOOLEAN,
          FIELD_DECIMAL DECIMAL(10,2),
          CREATED_AT TIMESTAMP,
          UPDATED_AT TIMESTAMP
        )
      SQL
      puts "✓ Test table SIS_TESTS created"
    end

    # Define test model - Rails convention uses lowercase
    unless defined?(SisTest)
      class SisTest < ActiveRecord::Base
        self.table_name = "sis_tests"
        self.primary_key = "id"
      end
    end

    SisTest.reset_column_information
  end

  config.after(:suite) do
    begin
      ActiveRecord::Base.connection_pool.disconnect! if ActiveRecord::Base.connected?
      is_local = !ENV["FIREBIRD_HOST"] && !DB_PATH.include?(":")
      File.delete(DB_PATH) if is_local && File.exist?(DB_PATH)
      puts "✓ Test cleanup completed"
    rescue StandardError
      nil
    end
  end

  config.before(:each) do
    # Ensure connection is active before each test
    begin
      unless ActiveRecord::Base.connection.active?
        ActiveRecord::Base.establish_connection(DB_CONFIG)
      end
    rescue StandardError
      ActiveRecord::Base.establish_connection(DB_CONFIG)
    end

    # Clean table data using Rails delete_all
    SisTest.delete_all if connection_table_exists?(:sis_tests)
    SisTest.reset_column_information if defined?(SisTest)
  end

  def connection_table_exists?(name)
    ActiveRecord::Base.connection.table_exists?(name)
  end
end
