# spec/spec_helper.rb
require "bundler/setup"

# Load Rails environment for adapter registration
require "active_record"
require "fb"
require "firebird_adapter"

require "rspec"

DB_PATH = ENV["FIREBIRD_DATABASE"] || File.expand_path("test.fdb", __dir__)
DB_CONFIG = {
  adapter: "firebird",
  database: DB_PATH,
  username: "sysdba",
  password: "masterkey",
  charset: "UTF8",
  downcase: false,
  host: ENV["DB_HOST"] || "localhost"
}.freeze
is_local_db = !ENV["FIREBIRD_HOST"] && !DB_PATH.include?(":")
File.delete(DB_PATH) if is_local_db && File.exist?(DB_PATH)

if is_local_db || !File.exist?(DB_PATH)
  begin
    ::Fb::Database.create(
      database: DB_PATH,
      user: "SYSDBA",
      password: "masterkey"
    )
  rescue StandardError => e
    puts "Note: Database may already exist or is remote: #{e.message}"
  end
end

# Configure RSpec
RSpec.configure do |config|
  config.before(:suite) do
    ActiveRecord::Base.establish_connection(DB_CONFIG)
    connection = ActiveRecord::Base.connection

    # Create table - Firebird stores names in uppercase internally
    unless connection.table_exists?(:sis_tests)
      connection.execute(<<-SQL)
        CREATE TABLE SIS_TESTS (
          ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          FIELD_VARCHAR BLOB SUB_TYPE TEXT,
          FIELD_CHAR CHAR(10),
          FIELD_DATE DATE,
          FIELD_SMALLINT INTEGER,
          FIELD_INTEGER INTEGER,
          FIELD_DOUBLE_PRECISION DOUBLE PRECISION,
          FIELD_BLOB_TEXT BLOB SUB_TYPE TEXT,
          FIELD_BLOB_BINARY BLOB SUB_TYPE BINARY,
          FIELD_BOOLEAN BOOLEAN,
          FIELD_DECIMAL DECIMAL(10,2),
          CREATED_AT TIMESTAMP,
          UPDATED_AT TIMESTAMP
        )
      SQL
    end

    # Define model - Rails convention uses lowercase
    unless defined?(SisTest)
      class SisTest < ActiveRecord::Base
        self.table_name = "sis_tests"
        self.primary_key = "id"
      end
    end

    # Reset column information
    SisTest.reset_column_information
  end

  config.after(:suite) do
    ActiveRecord::Base.connection_pool.disconnect! if ActiveRecord::Base.connected?
    is_local = !ENV["FIREBIRD_HOST"] && !DB_PATH.include?(":")
    File.delete(DB_PATH) if is_local && File.exist?(DB_PATH)
  rescue StandardError
    nil
  end

  config.before(:each) do
    # Ensure connection is active before each test
    begin
      ActiveRecord::Base.establish_connection(DB_CONFIG) unless ActiveRecord::Base.connection.active?
    rescue StandardError
      ActiveRecord::Base.establish_connection(DB_CONFIG)
    end

    # Clean table data using Rails delete_all
    SisTest.delete_all if table_exists?(:sis_tests)
    # Reset column information to avoid stale cache issues
    SisTest.reset_column_information if defined?(SisTest)
  end

  def table_exists?(name)
    ActiveRecord::Base.connection.table_exists?(name)
  end
end
