# frozen_string_literal: true

require "spec_helper"
require_relative "../lib/firebird_adapter/user_access"

RSpec.describe "User Access Tests" do
  let(:connection) { ActiveRecord::Base.connection }

  describe "Non-SYSDBA user connections" do
    it "can create and connect as basic user" do
      # Configuración para usuario básico
      user_config = FirebirdAdapter::UserAccess.connection_config(:basic_user, "spec/test_user.fdb")

      # Primero crear el usuario con SYSDBA
      begin
        connection.execute(FirebirdAdapter::UserAccess.create_user_sql(:basic_user))
      rescue StandardError => e
        puts "User might already exist: #{e.message}"
      end

      # Crear tabla de prueba para el usuario
      connection.execute(<<~SQL)
        CREATE TABLE USER_TEST_TABLE (
          ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          NAME VARCHAR(100),
          EMAIL VARCHAR(255)
        )
      SQL

      # Dar permisos al usuario
      connection.execute(FirebirdAdapter::UserAccess.grant_permissions_sql("USER_TEST_TABLE", :basic_user))

      # Conectar como el nuevo usuario
      begin
        ActiveRecord::Base.establish_connection(user_config)
        user_connection = ActiveRecord::Base.connection

        # Probar operaciones básicas
        expect(user_connection.active?).to be true

        # Insertar datos
        user_connection.execute(<<~SQL)
          INSERT INTO USER_TEST_TABLE (NAME, EMAIL)#{" "}
          VALUES ('Test User', 'test@example.com')
        SQL

        # Consultar datos
        result = user_connection.execute("SELECT COUNT(*) FROM USER_TEST_TABLE")
        expect(result.first.first).to eq(1)

        puts "✅ Usuario no-SYSDBA conectado y funcionando correctamente!"
      ensure
        # Restaurar conexión original
        db_config = {
          adapter: "firebird",
          database: "spec/test.fdb",
          username: "sysdba",
          password: "masterkey",
          charset: "UTF8",
          downcase: true
        }
        ActiveRecord::Base.establish_connection(db_config)
      end
    end

    it "supports different user roles" do
      # Probar diferentes configuraciones de usuario
      basic_config = FirebirdAdapter::UserAccess.connection_config(:basic_user, "test.fdb")
      readonly_config = FirebirdAdapter::UserAccess.connection_config(:readonly_user, "test.fdb")
      writer_config = FirebirdAdapter::UserAccess.connection_config(:writer_user, "test.fdb")

      expect(basic_config[:username]).to eq("BASIC_USER")
      expect(readonly_config[:username]).to eq("READONLY_USER")
      expect(writer_config[:username]).to eq("WRITER_USER")

      expect(readonly_config[:role]).to eq("READONLY_ROLE")
      expect(writer_config[:role]).to eq("WRITER_ROLE")
    end

    it "generates correct SQL for user creation" do
      sql = FirebirdAdapter::UserAccess.create_user_sql(:admin_user)

      expect(sql).to include("CREATE USER ADMIN_USER")
      expect(sql).to include("PASSWORD 'admin_pass'")
      expect(sql).to include("CREATE ROLE ADMIN_ROLE")
      expect(sql).to include("GRANT ADMIN_ROLE TO ADMIN_USER")
    end

    it "generates correct SQL for permissions" do
      sql = FirebirdAdapter::UserAccess.grant_permissions_sql("TEST_TABLE", :writer_user)

      expect(sql).to include("GRANT SELECT, INSERT, UPDATE, DELETE")
      expect(sql).to include("ON TEST_TABLE")
      expect(sql).to include("TO WRITER_USER")
    end
  end
end
